version: "3.8"

services:
  airflow:
    image: apache/airflow:2.9.1-python3.10
    container_name: airflow
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: bash -c "
      airflow db migrate &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password 7W899fz4fRAW9mpk &&
      airflow scheduler &
      exec airflow webserver"